member/urls.py
from django.urls import path
from . import views

app_name = "member"

urlpatterns = [
    path('detail/<int:id>/', views.detail, name = "detail"),
    path('training_detail/<int:id>/', views.training_detail, name="training_detail"),
]

pt/urls.py
from django.contrib import admin
from django.urls import path,include
from user import urls as user_urls
from member import urls as member_urls
from trainer import urls as trainer_urls
from user.views import dashboard

#For Media files
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',dashboard, name = "dashboard"),
    path('user/',include(user_urls)),
    path('member/', include(member_urls)),
    path('trainer/', include(trainer_urls)),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trainer/urls.py
from django.urls import path
from . import views

app_name = "trainer"

urlpatterns = []

urls.py
from django.contrib import admin
from django.urls import path,include
from user import urls as user_urls
from member import urls as member_urls
from trainer import urls as trainer_urls
from user.views import dashboard

#For Media files
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',dashboard, name = "dashboard"),
    path('user/',include(user_urls)),
    path('member/', include(member_urls)),
    path('trainer/', include(trainer_urls)),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trainer/models.py
from django.db import models

class Trainer(models.Model):
    user = models.OneToOneField("auth.user",on_delete=models.CASCADE,verbose_name="Uye")
    def __str__(self):
        return self.user.username

member/forms.py
from django import forms
from .models import Member,TrainingTransaction
from django.contrib.auth.models import User
from django.utils import timezone


class MemberAssigmentForm(forms.ModelForm):
    trainer = forms.ModelChoiceField(queryset=User.objects.all().filter(profile__user_grup="Eğitmen"))
    def clean(self):
        trainer = self.cleaned_data.get("trainer")
        values = {
            "trainer":trainer
        }
        return values


class TrainingTransactionForm(forms.ModelForm):

    class Meta:
        model = TrainingTransaction
        #fields = '__all__'
        fields ={'trainer','date','time','note'}
    list_of_hour ={
            (6,"06:00"),
            (7,"07:00"),
            (8, "08:00"),
            (9, "09:00"),
            (10, "10:00"),
            (11, "11:00"),
            (12, "12:00"),
            (13, "13:00"),
            (14, "14:00"),
            (15, "15:00"),
            (16, "16:00"),
            (17, "17:00"),
            (18, "18:00"),
            (19, "19:00"),
            (20, "20:00"),
            (21, "21:00"),
            (22, "22:00"),
            (23, "23:00"),
            (24, "24:00"),
            (1, "01:00"),
            (2, "02:00"),
            (3, "03:00"),
            (4, "04:00"),
            (5, "05:00"),}
    trainer = forms.ModelChoiceField(queryset=User.objects.all().filter(profile__user_grup="Eğitmen"))
   # member = forms.ModelChoiceField(queryset=User.objects.all().filter(profile__user_grup="Uye"))
    date = forms.DateField(required=True, widget=forms.SelectDateWidget(years=timezone.now().year), label="Tarih")
    time = forms.ChoiceField(choices=list_of_hour,label='Saat')
    note = forms.Textarea()

trainer/views.py
from django.shortcuts import render

# Create your views here.

templates/trainer/dashboard.html
{% extends "layout.html" %}
{% load static %}
{% block head %}
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'member/css/member_list.css'%}">
{% endblock head %}


{% block body %}


<div class="container">
<div class="row">
	<div class="col-lg-12">
		<div class="main-box clearfix">
			<div class="table-responsive">
				<table class="table user-list">
					<thead>
						<tr>
							<th><span>Üye</span></th>
							<th><span>Doğum Tarihi</span></th>
							<th class="text-center"><span>Statu</span></th>
							<th><span>Cep No</span></th>
							<th>&nbsp;</th>
						</tr>
					</thead>
					<tbody>

                      <div class="col-md-6 offset-md-0">
                            {% if request.user.is_authenticated %}
                                 {% if users %}
                                  {% for user in users  %}
                                    <tr>
                                        <td>
                                            {% if user.profile.image_profile %}
                                                <img src={{user.profile.image_profile.url}} alt="" style="width:50px;height:50px;" >
                                                <a href="{% url 'member:training_detail' user.id%}" class="user-link">{{user.first_name}} {{user.last_name}}</a>
                                                <span class="user-subhead">{{user.profile.gender}}</span>
                                            {% else %}
                                                <img src="{% static 'img/user.png'%}" alt="">
                                                <a href="{% url 'member:training_detail' user.id%}" class="user-link">{{user.first_name}} {{user.last_name}}</a>
                                                <span class="user-subhead">{{user.profile.gender}}  </span>
                                            {% endif %}


                                        </td>
                                        <td>
                                            {{user.profile.birthday}}
                                        </td>
                                        <td class="text-center">
                                            <span class="badge badge-warning">Inactive</span>
                                        </td>
                                        <td>
                                            <a href="#">
                                                {{user.profile.phone_number}}

                                            </a>
                                        </td>
                                        <td style="width: 20%;">
                                            <a href="{% url 'member:detail' user.id%}" class="table-link">
                                                <span class="fa-stack">
                                                    <i class="fa fa-square fa-stack-2x"></i>
                                                    <i class="fa fa-search-plus fa-stack-1x fa-inverse"></i>
                                                </span>
                                            </a>
                                            <a data-toggle="modal" data-target="#exampleModal" class="table-link">
                                                <span class="fa-stack">
                                                    <i class="fa fa-square fa-stack-2x"></i>
                                                    <i class="fa fa-user-plus fa-stack-1x fa-inverse"></i>
                                                </span>
                                            </a>
                                            <a href="#" class="table-link danger">
                                                <span class="fa-stack">
                                                    <i class="fa fa-square fa-stack-2x"></i>
                                                    <i class="fa fa-comment fa-stack-1x fa-inverse"></i>
                                                </span>
                                            </a>
                                        </td>
                                    </tr>
                                  {% endfor %}
                                {% else %}
                                  <div class="alert alert-danger">Atanmış üye bulunamadı</div>
                                {% endif %}

                            {% endif %}
                        <br>
                      </div>

					</tbody>
				</table>
			</div>
            <!--
			<ul class="pagination pull-right">
				<li><a href="#"><i class="fa fa-chevron-left"></i></a></li>
				<li><a href="#">1</a></li>
				<li><a href="#">2</a></li>
				<li><a href="#">3</a></li>
				<li><a href="#">4</a></li>
				<li><a href="#">5</a></li>
				<li><a href="#"><i class="fa fa-chevron-right"></i></a></li>
			</ul>
			-->
		</div>
	</div>
</div>
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <form enctype="multipart/form-data" class="form" method="post" id="registrationForm">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">--{{user.first_name}} {{user.last_name}}--</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <div class="modal-body">
            {% csrf_token%}
            {{form.media}}
            <div class="form-row">
                <div class="form-group col-6">
                    <label for="training_date">Gün</label>
                    <input type="date" class="form-control" id="training_date" name="date" value={{ date|date:'Y-m-d' }}>
                </div>


                <div class="form-group col-6">
                    <label for="id_hour">Saat</label>
                     <select name="time " class="select form-control" id="id_hour">
                        <option selected value={{time_now}}> {{time_now}}</option>

                        {% for time in time %}

                        <option value={{time}}> {{time}}</option>
                        {% endfor %}
                     </select>
                </div>
            </div>



            <label for="id_trainer">Eğitmen</label>
            <select name="trainer" class="select form-control" id="id_trainer">
                {% if request.user.profile.user_grup == 'Eğitmen' %}
                    <option selected value={{ request.user.id }}>{{ request.user }}</option>
                {% else %}
                    <option value= {{form.trainer}}</option>
                {% endif %}
            </select>




          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Save changes</button>
          </div>

      </form>

    </div>
  </div>
</div>

{% endblock body %}