pt/urls.py
from django.contrib import admin
from django.urls import path,include
from user import urls as user_urls
from member import urls as member_urls
from trainer import urls as trainer_urls
from user.views import dashboard

#For Media files
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',dashboard, name = "dashboard"),
    path('user/',include(user_urls)),
    path('member/', include(member_urls)),
    path('trainer/', include(trainer_urls)),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.contrib import admin
from django.urls import path,include
from user import urls as user_urls
from member import urls as member_urls
from trainer import urls as trainer_urls
from user.views import dashboard

#For Media files
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',dashboard, name = "dashboard"),
    path('user/',include(user_urls)),
    path('member/', include(member_urls)),
    path('trainer/', include(trainer_urls)),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('register/member/',  views.register_member, name = "register_member"),
    path('register/trainer/', views.register_trainer, name = "register_trainer"),
    path('login/', views.log_in, name = "login"),
    path('logout/', views.log_out, name = "logout"),
    path('dashboard/', views.dashboard, name = "dashboard"),
]

templates/includes/navbar.html
{% load static %}


<!-- <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" id="bootstrap-css">  -->
<!--<link rel="stylesheet" href="{% static 'css/bootstrap-material-design 4.1.1.min.css'%}"> -->



<!-- <script src="{% static 'js/bootstrap.min.js'%}"></script> -->
<!-- <script src="{% static 'js/jquery-3.2.1.min.js'%}"></script> -->


<!--

<link rel="stylesheet" href="{% static 'css/navbar.css'%}">
<link rel="stylesheet" href="{% static 'css/navbar_fonts.css'%}">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">





<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons">
<link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
-->

<!------ Include the above in your HEAD tag https://bootsnipp.com/snippets/WagVr ---------->

<nav class="navbar navbar-default navbar-expand-lg fixed-top">
    <div class="container">
        <a href="{% url 'user:dashboard'%}" class="profile-photo nav-link">
            <div class="profile-photo-small">
                {% if request.user.profile.image_profile %}
                    <img src={{request.user.profile.image_profile.url}} alt="Circle Image" class="rounded-circle img-fluid">
                {% else %}
                    <img src= {% static 'img/user.png'%} alt="Circle Image" class="rounded-circle img-fluid">
                {% endif %}
            </div>

            <div  >
                <div>{{request.user.first_name}} {{request.user.last_name}} <a> ({{request.user.profile.user_grup}})</a></div>
            </div>

        <div class="ripple-container"></div>
        </a>

        <div class="navbar-translate">
            <a class="navbar-brand" href="{% url 'user:dashboard'%}"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon">a</span>
                <span class="navbar-toggler-icon">b</span>
                <span class="navbar-toggler-icon">c</span>
            </button>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="{% url 'user:register_member'%}" class="btn btn-outline-info btn-raised btn-round " >
                        Üye Kayıt
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'user:register_trainer'%}" class="btn btn-outline-secondary btn-raised btn-round">
                        Eğitmen
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'user:logout'%}" class="btn btn-rose btn-raised btn-round" >
                        Çıkış
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/includes/navbar_rv1.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="/">
        {% if request.user.is_authenticated %}
        PT  {{request.user.username}} {{request.user.groups.all.0}}
        {% else %}
        PT
        {% endif %}
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">

 <!--
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">xxxxx <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#">xxxx <span class="sr-only">(current)</span></a>
        </li>
      </ul>
 -->


      <ul class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}
            {% if request.user.is_staff %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'user:register_member'%}">Üye Kayıt <span class="sr-only">(current)</span></a>
                </li>


                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'user:register_trainer'%}">Eğitmen Kayıt <span class="sr-only">(current)</span></a>
                </li>

            {% endif %}



            <li class="nav-item active">
                <a class="nav-link" href="{% url 'user:logout'%}">Çıkış Yap <span class="sr-only">(current)</span></a>
            </li>

<!--
            <li class="nav-item active">
                <a class="nav-link" href="/admin">Admin <span class="sr-only">(current)</span></a>
            </li>
-->
        {% else %}


            <li class="nav-item active">
              <a class="nav-link" href="{% url 'user:login'%}">Giriş yap <span class="sr-only">(current)</span></a>
            </li>
        {% endif %}



      </ul>


    </div>
  </nav>

templates/includes/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>