pt/urls.py
from django.contrib import admin
from django.urls import path,include
from user import urls as user_urls
from member import urls as member_urls
from trainer import urls as trainer_urls
from user.views import dashboard

#For Media files
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',dashboard, name = "dashboard"),
    path('user/',include(user_urls)),
    path('member/', include(member_urls)),
    path('trainer/', include(trainer_urls)),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.contrib import admin
from django.urls import path,include
from user import urls as user_urls
from member import urls as member_urls
from trainer import urls as trainer_urls
from user.views import dashboard

#For Media files
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',dashboard, name = "dashboard"),
    path('user/',include(user_urls)),
    path('member/', include(member_urls)),
    path('trainer/', include(trainer_urls)),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('register/member/',  views.register_member, name = "register_member"),
    path('register/trainer/', views.register_trainer, name = "register_trainer"),
    path('login/', views.log_in, name = "login"),
    path('logout/', views.log_out, name = "logout"),
    path('dashboard/', views.dashboard, name = "dashboard"),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from member.models import Member
from trainer.models import Trainer

from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    list_of_group = [('Uye', 'Uye'), ('Eğitmen', 'Eğitmen'), ('Yönetici', 'Yönetici'),]
    list_of_gender = [('Erkek', 'Erkek'), ('Kadın', 'Kadın'), ]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_grup = models.CharField(max_length=10,choices=list_of_group,default='Uye')

    gender = models.CharField(max_length=10, choices=list_of_gender, default='Diğer')
    phone_number = models.IntegerField(verbose_name="Telefon", blank=False,default=0)
    birthday = models.DateField(verbose_name="Dogum Tarihi",blank=True, null=True)
    image_profile = models.FileField(blank=True, null=True,upload_to='member_profile_image',verbose_name="Fotoğraf Ekleyin")
    def __str__(self):
        return self.user.username
# Profile Table Create
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

user/forms.py
from django import forms
import datetime


class LoginForm(forms.Form):
    username = forms.CharField(label="Kullanıcı Adı")
    password = forms.CharField(label="Password", widget=forms.PasswordInput)


class RegisterForm(forms.Form):
    list_of_gender = [('Erkek','Erkek'),('Kadin','Kadin'),]
    list_of_group = [('Uye', 'Uye'), ('Eğitmen', 'Eğitmen'), ('Yönetici', 'Yönetici'), ]
    #username = forms.CharField(max_length=50, label="Kullanıcı Adı")

    first_name = forms.CharField(max_length=50, label="Ad")
    last_name = forms.CharField(max_length=50, label="Soyad")
    password = forms.CharField(max_length=10, label="Parola", widget=forms.PasswordInput)
    confirm = forms.CharField(max_length=10, label="Parola doğrula", widget=forms.PasswordInput)
    birthday = forms.DateField(required=False,widget=forms.DateInput(),label="Dogum Tarihi" )
    gender = forms.ChoiceField(choices=list_of_gender,label="Cinsiyet",widget=forms.Select())
    phone_number = forms.IntegerField(label="Telefon",required=True)
    image_profile = forms.FileField(required=False, label="Profil Fotoğrafı")

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['gender'].label = False

    def clean(self):
        #username = self.cleaned_data.get("username")
        first_name = self.cleaned_data.get("first_name")
        last_name = self.cleaned_data.get("last_name")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")
        gender = self.cleaned_data.get("gender")
        birthday = self.cleaned_data.get("birthday")
        phone_number = self.cleaned_data.get("phone_number")
        image_profile = self.cleaned_data.get("image_profile")
        if password and confirm:
            if password != confirm:
                raise forms.ValidationError("Parolalar uyuşmuyor...")
            else:
                pass
        else:
            raise forms.ValidationError("Parola alanları girilmeli...")
        values = {

            "password": password,
            "first_name":first_name,
            "last_name": last_name,
            "gender": gender,
            "birthday": birthday,
            "phone_number":phone_number,
            "image_profile":image_profile
        }
        return values

user/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm,LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from member.models import Member
from trainer.models import Trainer
from user.models import Profile


@login_required(login_url="user:login")
def register_member(request):
    form = RegisterForm(request.POST or None,request.FILES or None)
    trainers = User.objects.filter(profile__user_grup="Eğitmen")

    print("************************  username:  ", request.POST.get('username'))
    print("************************  password:  ", request.POST.get('password'))
    print("************************  confirm:  ", request.POST.get('confirm'))
    print("************************  first_name:  ", request.POST.get('first_name'))
    print("************************  last_name:  ", request.POST.get('last_name'))
    print("************************  gender:  ", request.POST.get('gender'))
    print("************************  birthday:  ", request.POST.get('birthday'))
    print("************************  phone_number:  ", request.POST.get('phone_number'))
    print("************************  image_profile:  ", request.POST.get('image_profile'))

    if form.is_valid():
        password = form.cleaned_data.get("password")
        first_name = form.cleaned_data.get("first_name").capitalize()
        last_name = form.cleaned_data.get("last_name").capitalize()

        gender = form.cleaned_data.get("gender")
        birthday = form.cleaned_data.get("birthday")
        phone_number = form.cleaned_data.get("phone_number")
        image_profile = form.cleaned_data.get("image_profile")
        username =first_name.lower()+"."+last_name.lower()
        try:
            newUser = User(username=username, first_name=first_name, last_name=last_name)
            newUser.set_password(password)
            newUser.save()

            print("************************ newUser.id", newUser.id)
            newProfile = Profile.objects.get(user_id=newUser.id)
            newProfile.image_profile = image_profile
            newProfile.user_grup = "Uye"
            newProfile.phone_number=phone_number
            newProfile.birthday=birthday
            newProfile.gender = gender
            newProfile.save()

            newMember = Member(user=newUser)
            newMember.save()

            # login(request, newUser)

            #newMember = Member(member=newUser, gender=gender, birthday=birthday, phone_number=phone_number,image_profile=image_profile)
            #newMember.save()

            messages.success(request, 'Kullanıcı başarı ile kayıt edildi.')

            return redirect("user:dashboard")
        except:

            if User.objects.filter(username=username).exists():
                messages.info(request, 'Böyle bir kullancı var')
            else:
                raise


    else:

        if request.POST:
            messages.info(request, 'Kullanıcı kayıt edilemedi.')
        context = {
            "form": form
        }
        for x in form:
            print(x.value())
        return render(request, "user/register.html", context=context)


    context = {
        "form": form,
        "user_grup": "Member",
        'trainers':trainers
    }
    return render(request, "user/register.html", context=context)



@login_required(login_url="user:login")
def register_trainer(request):
    form = RegisterForm(request.POST or None,request.FILES or None)
    members = User.objects.filter(profile__user_grup="Uye")
    if form.is_valid():
        password = form.cleaned_data.get("password")
        first_name = form.cleaned_data.get("first_name").capitalize()
        last_name = form.cleaned_data.get("last_name").capitalize()

        gender = form.cleaned_data.get("gender")
        birthday = form.cleaned_data.get("birthday")
        phone_number = form.cleaned_data.get("phone_number")
        image_profile = form.cleaned_data.get("image_profile")
        username =first_name.lower()+"."+last_name.lower()
        try:

            newUser = User(username=username, first_name=first_name, last_name=last_name)
            newUser.set_password(password)
            newUser.save()

            newProfile = Profile.objects.get(user_id=newUser.id)
            newProfile.image_profile = image_profile
            newProfile.user_grup = "Eğitmen"
            newProfile.phone_number=phone_number
            newProfile.birthday=birthday
            newProfile.gender = gender
            newProfile.save()

            newTrainer = Trainer(user=newUser)
            newTrainer.save()

            messages.success(request, 'Kullanıcı başarı ile kayıt edildi.')
            return redirect("user:dashboard")
        except:

            if User.objects.filter(username=username).exists():
                messages.info(request, 'Böyle bir kullancı var')
            else:
                raise
    else:

        if request.POST:
            messages.info(request, 'Kullanıcı kayıt edilemedi.')

    context = {
        "form": form,
        "user_grup":"Trainer",
        "members":members
    }
    return render(request, "user/register.html", context=context)

def log_in(request):
    form = LoginForm(request.POST or None)
    context = {
        "form":form
    }
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(username=username,password=password)
        if user is None:
            messages.info(request, "Böyle bir kullanıcı yok veya parola hatalı")
            return render(request,"user/login.html",context=context)
        messages.success(request,"Başarı ile giriş yaptınız")
        login(request,user)
        #return render(request,"trainer/dashboard.html")
        return redirect("user:dashboard")
    return render(request,"user/login.html",context=context)



def log_out(request):
    logout(request)
    messages.success(request,"Sistemden çıkış yaptınız")
    return redirect("user:dashboard")

@login_required(login_url="user:login")
def dashboard(request):
    #x = Member.objects.all().order_by("-id")
    #y = User.objects.exclude(id__in=Member.objects.all().values('member_id'))

    x= User.objects.all().filter(profile__user_grup="Uye").order_by("-id")
    context = {

        "users": x
    }
    return render(request, "trainer/dashboard.html", context=context)

templates/user/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
     <!--
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'user/css/login.css'%}">
<!--
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
-->

    <title>PT Login</title>
</head>
<body>


<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->
    <h2>Hoşgeldin</h2>
    <!-- Icon -->
    <div class="fadeIn first">
      <!--
      <img src="http://ani-theme.strapui.com/images/flat-avatar.png"  id="icon" alt="User Icon" />
      -->
       <img src="{% static 'img/login.png'%}"  id="icon" alt="User Icon" />
    </div>

    <!-- Login Form -->
    <form method="post">
      {% csrf_token%}
      <input type="text" id="login" class="fadeIn second" name="username" placeholder="kullanıcı adı">
      <input type="text" id="password" class="fadeIn third" name="password" placeholder="şifre">
      <input type="submit" class="fadeIn fourth" value="Giriş Yap">
    </form>

      <!-- Error Messages -->
     <div class="container">
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == "info" %}
                    <div {% if message.tags %} class="alert alert-danger"{% endif %}>{{ message }}</div>
                {% else %}
                    <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
                {% endif %}
            {% endfor %}
        {% endif %}

        {% block body %}
        {% endblock %}

    </div>
    <!-- Remind Passowrd -->
    <div id="formFooter">
      <a class="underlineHover" href="#">Şifremi Unuttum?</a>
    </div>

  </div>
</div>

<script src="{% static 'js/jquery-3.2.1.min.js'%}"></script>
<script src="{% static 'js/bootstrap.min.js'%}"></script>

</body>
</html>

templates/user/register.html
{% extends "layout.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
<!--
    <link rel="stylesheet" href="{% static 'user/css/register.css'%}">
    <link rel="stylesheet" href="https://bootswatch.com/4/simplex/bootstrap.min.css"/>
-->

{% endblock head %}


{% block body %}
<!-- Default form contact
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
-->
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <form enctype="multipart/form-data" class="form" method="post" id="registrationForm">
                        {% csrf_token%}
                        {{form.media}}
                        <div class="card-title mb-sm-1">
                            <div class="d-flex justify-content-start">

                                <div class="image-container">
                                    <img src="http://placehold.it/150x180" name="imgProfile" id="image_profile" style="width: 150px; height: 180px" class="avatar img-thumbnail" alt="avatar" />
                                    <h6></h6>
                                    <label for="fileupload" class="btn btn-outline-danger" style="width: 150px">
                                        Resim yükle
                                        <input type="file" name="image_profile" class="file-upload" id="fileupload" hidden>
                                    </label>
                                </div>

                                <div class="userData ml-3">
                                   {% if user_grup == "Trainer" %}
                                     <h2 class="d-block" style="font-size: 1.5rem; font-weight: bold"><a href="javascript:void(0);">Yeni Eğitmen Kaydı </a></h2>
                                   {% else %}
                                     <h2 class="d-block" style="font-size: 1.5rem; font-weight: bold"><a href="javascript:void(0);">Yeni Üye Kaydı </a></h2>
                                   {% endif %}


                                    <h6 class="d-block"><a href="javascript:void(0)">0</a> Bakiye</h6>
                                    <h6 class="d-block"><span class="pull-left"><strong>Bakiye </strong></span> <a href="javascript:void(0)"> 0</a></h6>
                                    <h6 class="d-block"><span class="pull-left"><strong>Order Amount </strong></span> <a href="javascript:void(0)"> 0</a></h6>
                                </div>

                                <div class="ml-auto">
                                    <input type="button" class="btn btn-primary d-none" id="btnDiscard" value="Discard Changes" />
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-12">
                                <ul class="nav nav-tabs mb-4" id="myTab" role="tablist">
                                    <li class="nav-item">
                                        <a class="nav-link active" id="basicInfo-tab" data-toggle="tab" href="#basicInfo" role="tab" aria-controls="basicInfo" aria-selected="true">Genel Bilgi</a>
                                    </li>

                                    <li class="nav-item">
                                        <a class="nav-link" id="connectedServices-tab" data-toggle="tab" href="#connectedServices" role="tab" aria-controls="connectedServices" aria-selected="false">Ödeme Bilgisi</a>
                                    </li>

                                    <li class="nav-item">
                                        <a class="nav-link" id="connectedServices-tab" data-toggle="tab" href="#connectedServices" role="tab" aria-controls="connectedServices" aria-selected="false">Ders Paketleri</a>
                                    </li>
                                </ul>

                                <div class="tab-content ml-1" id="myTabContent">
                                    <div class="tab-pane fade show active" id="basicInfo" role="tabpanel" aria-labelledby="basicInfo-tab">
                                          <!-- Grid row -->
                                          <div class="form-row">
                                            <!-- Default input -->
                                            <div class="form-group col-md-6">
                                              <label for="firstname">İsim</label>
                                              <input type="text" class="form-control" id="firstname" name="first_name" placeholder="ad">
                                            </div>

                                            <!-- Default input -->
                                            <div class="form-group col-md-6">
                                              <label for="lastname">Soy İsim</label>
                                              <input type="text" class="form-control" id="lastname" name="last_name" placeholder="soyad">
                                            </div>
                                          </div>
                                          <!-- Grid row -->

                                          <!-- Grid row -->
                                          <div class="form-row">
                                            <!-- Default input -->
                                            <div class="form-group col-md-6">
                                              <label for="password">Şifre</label>
                                              <input type="password" class="form-control" id="password" name="password" placeholder="şifre">
                                            </div>
                                            <!-- Default input -->
                                            <div class="form-group col-md-6">
                                              <label for="passwordconfirm">Şifre (tekrar)</label>
                                              <input type="password" class="form-control" id="passwordconfirm" name="confirm" placeholder="şifre tekrar">

                                            </div>
                                          </div>
                                          <!-- Grid row -->

                                          <!-- Grid row -->
                                          <div class="form-row">
                                            <!-- Default input -->
                                            <div class="form-group col-md-4">
                                                <label for="id_gender">Cinsiyet</label>
                                                <select name="gender" class="select form-control" id="id_gender">
                                                  <option value="Erkek">Erkek</option>
                                                  <option value="Kadin">Kadin</option>
                                                </select>

                                            </div>


                                            <!-- Default input -->
                                            <div class="form-group col-md-4">
                                              <label for="birthday">Doğum Tarihi</label>
                                              <input type="date" format="YYYY/MM/DD" class="form-control" id="birthday" name="birthday">
                                            </div>
                                            <!-- Default input -->
                                            <div class="form-group col-md-4">
                                              <label for="phonenumber">Telefon</label>
                                              <input type="text" class="form-control" id="phonenumber" name="phone_number" placeholder="telefon">
                                            </div>
                                          </div>
                                          <!-- Grid row -->




                                          <div class="form-group">
                                             <div class="col-xs-12">
                                                  <button class="btn btn-sm btn-success" type="submit"><i class="glyphicon glyphicon-ok-sign"></i> Kaydet</button>
                                              </div>
                                          </div>

                                    </div>

                                    <div class="tab-pane fade" id="connectedServices" role="tabpanel" aria-labelledby="ConnectedServices-tab">

                                       <div class="row">

                                           <div class="col-md-6 offset-md-0">
                                                {% if request.user.is_authenticated %}
                                                     {% if trainers %}
                                                         {% for trainer in trainers  %}
                                                               <div class="list-group">
                                                                 <a href="#" class="list-group-item d-flex justify-content-between align-items-center list-group-item-warning">
                                                                     {{trainer.id}} {{trainer.first_name}} {{trainer.last_name}}
                                                                     <span class="badge badge-danger badge-pill">0</span>
                                                                 </a>

                                                               </div>

                                                         {% endfor %}

                                                    {% elif members %}
                                                         {% for member in members  %}
                                                               <div class="list-group">
                                                                 <a href="#" class="list-group-item d-flex justify-content-between align-items-center list-group-item-warning">
                                                                     {{member.id}} {{member.first_name}} {{member.last_name}}
                                                                     <span class="badge badge-danger badge-pill">0</span>
                                                                 </a>

                                                               </div>

                                                         {% endfor %}
                                                    {% else %}
                                                      <div class="alert alert-danger">Bir kayıt bulunamadı</div>
                                                    {% endif %}

                                                {% endif %}
                                            <br>
                                            </div>

                                        </div>
                                    </div>


                                </div>
                            </div>
                        </div>
                    </form>

                </div>

            </div>
        </div>
    </div>
</div>

<!-- Default form contact -->

{% endblock body %}

{% block scripts %}
    <script src="{% static 'user/js/register.js'%}"></script>
{% endblock scripts %}